version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - secret-key-token=${SECRETKEYTOKEN}
    ports:
      - "8080:8080"