name: Trigger deployment for kissa-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/frontend/**'
    - '.github/workflows/kissa-web-AutoDeployTrigger-d8d0e5c1-0030-4012-9375-44c29c2bdd33.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KISSAWEB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend 
          registryUrl: kissacontainer.azurecr.io
          registryUsername: ${{ secrets.KISSAWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KISSAWEB_REGISTRY_PASSWORD }}
          containerAppName: kissa-web
          resourceGroup: kissa-rg
          imageToBuild: kissacontainer.azurecr.io/kissa-web:${{ github.sha }}
          dockerfilePath: Dockerfile

     

